In [1]:

# import libraries
import pandas as pd

In [2]:

# load the data
df=pd.read_csv('/content/drive/MyDrive/fakenews/train.csv')

In [3]:

#the number of null values
df.isnull().sum().sum()

2554

In [4]:
# we have to remove the null values
df=df.dropna()
df.shape

(18285, 5)

In [5]:

#importing libraries related to text to vector conversion
from sklearn.feature_extraction.text import CountVectorizer

In [6]:

finaldf=df.copy()

In [7]:
finaldf.reset_index(inplace=True)


In [8]:
# text preporcessing stopwords removal and stemming
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [9]:

import nltk
import re # regurlar expression
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [10]:

# just an example for stemming and lemmatization
text='Benoît Hamon Wins French Socialist Party’s Presidential Nomination - The New York Times'
text=text.split()
#print(text)
review=[ps.stem(word) for word in text if not word in stopwords.words('english')]
#print(review)

In [11]:

corpus=[]
for i in range(0,len(finaldf)):
  review=re.sub('[^A-Za-z]', ' ',finaldf['title'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [12]:

# Apply count vectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()

In [13]:

y=finaldf['label']

In [14]:

#perfrom traina nd text split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.33,random_state=0)

In [15]:

count_df=pd.DataFrame(X_train,columns=cv.get_feature_names_out())
count_df.head()

aa  aaa  aap  aaron  ab  abandon  abandonado  abba  abbi  abbott  ...  \
0   0    0    0      0   0        0           0     0     0       0  ...   
1   0    0    0      0   0        0           0     0     0       0  ...   
2   0    0    0      0   0        0           0     0     0       0  ...   
3   0    0    0      0   0        0           0     0     0       0  ...   
4   0    0    0      0   0        0           0     0     0       0  ...   

   zulema  zulu  zumwalt  zur  zuschraubt  zvezda  zw  zweden  zweit  zwo  
0       0     0        0    0           0       0   0       0      0    0  
1       0     0        0    0           0       0   0       0      0    0  
2       0     0        0    0           0       0   0       0      0    0  
3       0     0        0    0           0       0   0       0      0    0  
4       0     0        0    0           0       0   0       0      0    0  

[5 rows x 13913 columns]

In [16]:

#multinomial navie bayes
from sklearn.naive_bayes import MultinomialNB
classfier=MultinomialNB()

In [17]:

from sklearn import metrics
import numpy as np
import itertools


In [18]:
classfier.fit(X_train,y_train)
y_pred=classfier.predict(X_test)
score=metrics.accuracy_score(y_test,y_pred)
score

0.8980944490472246

In [ ]:
#with lstm

In [20]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
voc_size1=5000

In [25]:
onehot_repr=[one_hot(words,voc_size1) for words in corpus]

In [26]:
onehot_repr

[[459, 4069, 538, 4683, 743, 2581, 2770, 206, 2720, 437],
 [74, 578, 562, 2350, 1738, 4873, 2465],
 [1700, 178, 3236, 1105],
 [4281, 2957, 4627, 3789, 3023, 3131],
 [2127, 1738, 3112, 238, 4007, 418, 1738, 107, 4569, 2087],
 [1446,
  4192,
  3587,
  1417,
  441,
  3745,
  4433,
  2221,
  661,
  561,
  541,
  1991,
  1326,
  1794,
  2465],
 [892, 2856, 4516, 4410, 1235, 4598, 717, 3611, 2694, 1090, 2717],
 [2261, 1548, 3532, 1291, 294, 4372, 3745, 4022, 2694, 1090, 2717],
 [1833, 2366, 1932, 3101, 4055, 3888, 3505, 2133, 3745, 1055],
 [4357, 2181, 672, 3448, 4376, 835, 2761, 387],
 [1679, 2160, 1601, 2868, 4024, 1189, 4131, 1132, 4265, 385, 200],
 [3789, 1724, 743, 3888, 3745, 294],
 [4839, 2304, 1963, 858, 1269, 3283, 2803, 312, 1829],
 [3214, 3419, 3001, 1928, 1053, 427, 1434, 2694, 1090, 2717],
 [4927, 3177, 3732, 4940, 4488, 2694, 1090, 2717],
 [1495, 151, 4114, 3582, 1586, 1139, 3737, 2898, 1717, 1195],
 [2311, 4286, 578],
 [4868, 847, 3395, 3177, 3745, 3834, 102, 2465],
 [1369, 11

In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [30]:
# emebeded represnetation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  459,
       4069,  538, 4683,  743, 2581, 2770,  206, 2720,  437], dtype=int32)

In [36]:
embedding_features=40
model=Sequential()
model.add(Embedding(voc_size1,embedding_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [37]:
len(embedded_docs)

18285

In [38]:
import numpy as np
X_final=np.array(embedded_docs)
y=np.array(y)

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_final,y,test_size=.3,random_state=1)

In [40]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 11s 38ms/step - loss: 0.3299 - accuracy: 0.8443 - val_loss: 0.1927 - val_accuracy: 0.9160
Epoch 2/10
200/200 [==============================] - 9s 46ms/step - loss: 0.1469 - accuracy: 0.9399 - val_loss: 0.1833 - val_accuracy: 0.9234
Epoch 3/10
200/200 [==============================] - 7s 35ms/step - loss: 0.1083 - accuracy: 0.9577 - val_loss: 0.2283 - val_accuracy: 0.9216
Epoch 4/10
200/200 [==============================] - 10s 48ms/step - loss: 0.0801 - accuracy: 0.9720 - val_loss: 0.2323 - val_accuracy: 0.9154
Epoch 5/10
200/200 [==============================] - 8s 42ms/step - loss: 0.0634 - accuracy: 0.9795 - val_loss: 0.3115 - val_accuracy: 0.9167
Epoch 6/10
200/200 [==============================] - 8s 38ms/step - loss: 0.0433 - accuracy: 0.9862 - val_loss: 0.3643 - val_accuracy: 0.9167
Epoch 7/10
200/200 [==============================] - 9s 47ms/step - loss: 0.0327 - accuracy: 0.9907 - val_loss: 0.3753 - val_accuracy: 0.90

In [45]:
y_pred=(model.predict(x_test) > 0.5).astype("int32")


172/172 [==============================] - 1s 6ms/step


In [42]:
predict_x=model.predict(x_test)
classes_x=np.argmax(predict_x,axis=1)

172/172 [==============================] - 2s 9ms/step


In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[2856  270]
 [ 223 2137]]
0.9101348888078746


In [51]:
from tensorflow.keras.layers import Dropout
embedding_features=40
model=Sequential()
model.add(Embedding(voc_size1,embedding_features,input_length=sent_length))
model.add(Dropout(.33))
model.add(LSTM(100))
model.add(Dropout(.33))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [52]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 15s 62ms/step - loss: 0.3432 - accuracy: 0.8446 - val_loss: 0.1969 - val_accuracy: 0.9147
Epoch 2/10
200/200 [==============================] - 9s 44ms/step - loss: 0.1546 - accuracy: 0.9366 - val_loss: 0.1842 - val_accuracy: 0.9244
Epoch 3/10
200/200 [==============================] - 12s 60ms/step - loss: 0.1165 - accuracy: 0.9566 - val_loss: 0.2123 - val_accuracy: 0.9202
Epoch 4/10
200/200 [==============================] - 11s 53ms/step - loss: 0.0847 - accuracy: 0.9699 - val_loss: 0.2341 - val_accuracy: 0.9216
Epoch 5/10
200/200 [==============================] - 9s 45ms/step - loss: 0.0649 - accuracy: 0.9785 - val_loss: 0.2623 - val_accuracy: 0.9172
Epoch 6/10
200/200 [==============================] - 10s 52ms/step - loss: 0.0477 - accuracy: 0.9834 - val_loss: 0.3171 - val_accuracy: 0.9169
Epoch 7/10
200/200 [==============================] - 10s 49ms/step - loss: 0.0339 - accuracy: 0.9897 - val_loss: 0.3436 - val_accuracy: 0

In [53]:
y_pred=(model.predict(x_test) > 0.5).astype("int32")
predict_x=model.predict(x_test)
classes_x=np.argmax(predict_x,axis=1)

172/172 [==============================] - 1s 6ms/step


In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[2867  259]
 [ 215 2145]]
0.913598250091141
