In [ ]:
# import nltk library
import nltk

In [ ]:
#text preprocessing tokenization we have to download punkt from nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# Tokenization main aim is dividing the paragraph into either sentences or words


In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [ ]:
para="The economy of India has transitioned from a mixed planned economy to a mixed middle-income developing social market economy and largest South Asian economy with notable public sector in strategic sectors.[50] It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP). According to the International Monetary Fund (IMF), on a per capita income basis, India ranked 139th by GDP (nominal) and 127th by GDP (PPP).[51] From independence in 1947 until 1991, successive governments followed Soviet model and promoted protectionist economic policies, with extensive Sovietization, state intervention, bureaucrat driven enterprises and economic regulation. This is characterised as dirigism, in the form of the Licence Raj.[52][53] The end of the Cold War and an acute balance of payments crisis in 1991 led to the adoption of a broad economic liberalisation in India and indicative planning.[54][55] Since the start of the 21st century, annual average GDP growth has been 6% to 7%.[50] The economy of the Indian subcontinent was the largest in the world for most of recorded history up until the onset of colonialism in early 19th century.[56][57][58] India accounts for 7.2% of the global economy in 2022 in PPP terms, and around 3.4% in nominal terms in 2022.[59][60]"

In [ ]:
#converting entire paragraph to list of sentences
nltk.sent_tokenize(para)

['The economy of India has transitioned from a mixed planned economy to a mixed middle-income developing social market economy and largest South Asian economy with notable public sector in strategic sectors.',
 "[50] It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP).",
 'According to the International Monetary Fund (IMF), on a per capita income basis, India ranked 139th by GDP (nominal) and 127th by GDP (PPP).',
 '[51] From independence in 1947 until 1991, successive governments followed Soviet model and promoted protectionist economic policies, with extensive Sovietization, state intervention, bureaucrat driven enterprises and economic regulation.',
 'This is characterised as dirigism, in the form of the Licence Raj.',
 '[52][53] The end of the Cold War and an acute balance of payments crisis in 1991 led to the adoption of a broad economic liberalisation in India and indicative planning.',
 '[54][55] Since the start of the 21

In [ ]:
#converting entire sentences into the words
sent="It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP)"

In [ ]:
nltk.word_tokenize(sent)

['It',
 'is',
 'the',
 'world',
 "'s",
 'fifth-largest',
 'economy',
 'by',
 'nominal',
 'GDP',
 'and',
 'the',
 'third-largest',
 'by',
 'purchasing',
 'power',
 'parity',
 '(',
 'PPP',
 ')']

In [ ]:
#spacy
import spacy

In [ ]:
nlp=spacy.load('en_core_web_sm')

In [ ]:
doc=nlp(para)

In [ ]:
doc

The economy of India has transitioned from a mixed planned economy to a mixed middle-income developing social market economy and largest South Asian economy with notable public sector in strategic sectors.[50] It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP). According to the International Monetary Fund (IMF), on a per capita income basis, India ranked 139th by GDP (nominal) and 127th by GDP (PPP).[51] From independence in 1947 until 1991, successive governments followed Soviet model and promoted protectionist economic policies, with extensive Sovietization, state intervention, bureaucrat driven enterprises and economic regulation. This is characterised as dirigism, in the form of the Licence Raj.[52][53] The end of the Cold War and an acute balance of payments crisis in 1991 led to the adoption of a broad economic liberalisation in India and indicative planning.[54][55] Since the start of the 21st century, annual average GDP

In [ ]:
sentspacy=[sent.text for sent in doc.sents]

In [ ]:
sentspacy

["The economy of India has transitioned from a mixed planned economy to a mixed middle-income developing social market economy and largest South Asian economy with notable public sector in strategic sectors.[50] It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP).",
 'According to the International Monetary Fund (IMF), on a per capita income basis, India ranked 139th by GDP (nominal) and 127th by GDP (PPP).[51] From independence in 1947 until 1991, successive governments followed Soviet model and promoted protectionist economic policies, with extensive Sovietization, state intervention, bureaucrat driven enterprises and economic regulation.',
 'This is characterised as dirigism, in the form of the Licence Raj.[52][53]',
 'The end of the Cold War and an acute balance of payments crisis in 1991 led to the adoption of a broad economic liberalisation in India and indicative planning.[54][55]',
 'Since the start of the 21st century, 

In [ ]:
words=[token.text for token in doc]

In [ ]:
words

['The',
 'economy',
 'of',
 'India',
 'has',
 'transitioned',
 'from',
 'a',
 'mixed',
 'planned',
 'economy',
 'to',
 'a',
 'mixed',
 'middle',
 '-',
 'income',
 'developing',
 'social',
 'market',
 'economy',
 'and',
 'largest',
 'South',
 'Asian',
 'economy',
 'with',
 'notable',
 'public',
 'sector',
 'in',
 'strategic',
 'sectors.[50',
 ']',
 'It',
 'is',
 'the',
 'world',
 "'s",
 'fifth',
 '-',
 'largest',
 'economy',
 'by',
 'nominal',
 'GDP',
 'and',
 'the',
 'third',
 '-',
 'largest',
 'by',
 'purchasing',
 'power',
 'parity',
 '(',
 'PPP',
 ')',
 '.',
 'According',
 'to',
 'the',
 'International',
 'Monetary',
 'Fund',
 '(',
 'IMF',
 ')',
 ',',
 'on',
 'a',
 'per',
 'capita',
 'income',
 'basis',
 ',',
 'India',
 'ranked',
 '139th',
 'by',
 'GDP',
 '(',
 'nominal',
 ')',
 'and',
 '127th',
 'by',
 'GDP',
 '(',
 'PPP).[51',
 ']',
 'From',
 'independence',
 'in',
 '1947',
 'until',
 '1991',
 ',',
 'successive',
 'governments',
 'followed',
 'Soviet',
 'model',
 'and',
 'promoted

In [ ]:
sent="It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP)"

In [ ]:
sent

"It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP)"

In [ ]:
word=nltk.word_tokenize(sent)

In [ ]:
word

['It',
 'is',
 'the',
 'world',
 "'s",
 'fifth-largest',
 'economy',
 'by',
 'nominal',
 'GDP',
 'and',
 'the',
 'third-largest',
 'by',
 'purchasing',
 'power',
 'parity',
 '(',
 'PPP',
 ')']

In [ ]:
len(word)

20

In [ ]:
# import stopwords library from nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stop_words=set(stopwords.words('english')) # to avoid the dulicates and standard practice we use set

In [ ]:
filtered_words=[words for words in word if words.lower()  not in stop_words]

In [ ]:
filtered_words

['world',
 "'s",
 'fifth-largest',
 'economy',
 'nominal',
 'GDP',
 'third-largest',
 'purchasing',
 'power',
 'parity',
 '(',
 'PPP',
 ')']

In [ ]:
word

['It',
 'is',
 'the',
 'world',
 "'s",
 'fifth-largest',
 'economy',
 'by',
 'nominal',
 'GDP',
 'and',
 'the',
 'third-largest',
 'by',
 'purchasing',
 'power',
 'parity',
 '(',
 'PPP',
 ')']

In [ ]:
sent="It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP)"

In [ ]:
import re # regular expression library


In [ ]:
abc=nltk.sent_tokenize(para)

In [ ]:
abc

['The economy of India has transitioned from a mixed planned economy to a mixed middle-income developing social market economy and largest South Asian economy with notable public sector in strategic sectors.',
 "[50] It is the world's fifth-largest economy by nominal GDP and the third-largest by purchasing power parity (PPP).",
 'According to the International Monetary Fund (IMF), on a per capita income basis, India ranked 139th by GDP (nominal) and 127th by GDP (PPP).',
 '[51] From independence in 1947 until 1991, successive governments followed Soviet model and promoted protectionist economic policies, with extensive Sovietization, state intervention, bureaucrat driven enterprises and economic regulation.',
 'This is characterised as dirigism, in the form of the Licence Raj.',
 '[52][53] The end of the Cold War and an acute balance of payments crisis in 1991 led to the adoption of a broad economic liberalisation in India and indicative planning.',
 '[54][55] Since the start of the 21

In [ ]:
corpus=[]
for i in range(len(abc)):
  print(i)
  review=re.sub('[^a-zA-Z]'," ",abc[i].lower())
  print(review)
  corpus.append(review)

0
the economy of india has transitioned from a mixed planned economy to a mixed middle income developing social market economy and largest south asian economy with notable public sector in strategic sectors 
1
     it is the world s fifth largest economy by nominal gdp and the third largest by purchasing power parity  ppp  
2
according to the international monetary fund  imf   on a per capita income basis  india ranked    th by gdp  nominal  and    th by gdp  ppp  
3
     from independence in      until       successive governments followed soviet model and promoted protectionist economic policies  with extensive sovietization  state intervention  bureaucrat driven enterprises and economic regulation 
4
this is characterised as dirigism  in the form of the licence raj 
5
         the end of the cold war and an acute balance of payments crisis in      led to the adoption of a broad economic liberalisation in india and indicative planning 
6
         since the start of the   st century  

In [ ]:
abc=corpus[1].strip()

In [ ]:
abc

'it is the world s fifth largest economy by nominal gdp and the third largest by purchasing power parity  ppp'

In [ ]:
from nltk.corpus import stopwords
tokens=word_tokenize(abc)
stop_words=set(stopwords.words('english'))

In [ ]:
filtered_sent=[token for token in tokens if token.lower() not in stop_words]

In [ ]:
filtered_sent

['world',
 'fifth',
 'largest',
 'economy',
 'nominal',
 'gdp',
 'third',
 'largest',
 'purchasing',
 'power',
 'parity',
 'ppp']

In [ ]:
# to do stemming we have to import porter stemmer library
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()


In [ ]:
word="knowledge"
stemmer.stem(word)

'knowledg'

In [ ]:
from nltk.stem import SnowballStemmer
stemmer=SnowballStemmer('english')

In [ ]:
word="knowledge"
stemmer.stem(word)

'knowledg'

In [ ]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

In [ ]:
word="knowledge"
stemmer.stem(word)

'knowledg'

['the economy of india has transitioned from a mixed planned economy to a mixed middle income developing social market economy and largest south asian economy with notable public sector in strategic sectors ',
 '     it is the world s fifth largest economy by nominal gdp and the third largest by purchasing power parity  ppp  ',
 'according to the international monetary fund  imf   on a per capita income basis  india ranked    th by gdp  nominal  and    th by gdp  ppp  ',
 '     from independence in      until       successive governments followed soviet model and promoted protectionist economic policies  with extensive sovietization  state intervention  bureaucrat driven enterprises and economic regulation ',
 'this is characterised as dirigism  in the form of the licence raj ',
 '         the end of the cold war and an acute balance of payments crisis in      led to the adoption of a broad economic liberalisation in india and indicative planning ',
 '         since the start of the   

In [ ]:
for i in corpus:
  words=word_tokenize(i)
  #print(words)
  for word in words:
    if word not in stop_words:
      print(word,"-->",stemmer.stem(word))

economy --> econom
india --> ind
transitioned --> transit
mixed --> mix
planned --> plan
economy --> econom
mixed --> mix
middle --> middl
income --> incom
developing --> develop
social --> soc
market --> market
economy --> econom
largest --> largest
south --> sou
asian --> as
economy --> econom
notable --> not
public --> publ
sector --> sect
strategic --> strategic
sectors --> sect
world --> world
fifth --> fif
largest --> largest
economy --> econom
nominal --> nomin
gdp --> gdp
third --> third
largest --> largest
purchasing --> purchas
power --> pow
parity --> par
ppp --> ppp
according --> accord
international --> intern
monetary --> monet
fund --> fund
imf --> imf
per --> per
capita --> capit
income --> incom
basis --> bas
india --> ind
ranked --> rank
th --> th
gdp --> gdp
nominal --> nomin
th --> th
gdp --> gdp
ppp --> ppp
independence --> independ
successive --> success
governments --> govern
followed --> follow
soviet --> soviet
model --> model
promoted --> promot
protectionist 

In [ ]:
# lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
for i in corpus:
  words=word_tokenize(i)
  #print(words)
  for word in words:
    if word not in stop_words:
      print(word,"-->",stemmer.stem(word),"  -->",lemmatizer.lemmatize(word))

economy --> econom   --> economy
india --> ind   --> india
transitioned --> transit   --> transitioned
mixed --> mix   --> mixed
planned --> plan   --> planned
economy --> econom   --> economy
mixed --> mix   --> mixed
middle --> middl   --> middle
income --> incom   --> income
developing --> develop   --> developing
social --> soc   --> social
market --> market   --> market
economy --> econom   --> economy
largest --> largest   --> largest
south --> sou   --> south
asian --> as   --> asian
economy --> econom   --> economy
notable --> not   --> notable
public --> publ   --> public
sector --> sect   --> sector
strategic --> strategic   --> strategic
sectors --> sect   --> sector
world --> world   --> world
fifth --> fif   --> fifth
largest --> largest   --> largest
economy --> econom   --> economy
nominal --> nomin   --> nominal
gdp --> gdp   --> gdp
third --> third   --> third
largest --> largest   --> largest
purchasing --> purchas   --> purchasing
power --> pow   --> power
parity -->

In [ ]:
# bag of words


In [1]:
# importing the libraries
import nltk

In [3]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""



In [4]:
len(paragraph)

2241

In [16]:
#cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [9]:
# to do stemming
ps=PorterStemmer()

In [10]:
# convert the paragraph into sentences
sentences=nltk.sent_tokenize(paragraph)

In [11]:
sentences

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.',
 'Why?',
 'Because we respect the freedom of others.That is why my \n               first vision is that of freedom.',
 'I believe that India got its first vision of \n               this in 1857, when we started the War of Independence.',
 'It is this freedom that\n               we must protect and nurture and build on.',
 'If we are not free, no one will respect us.',
 'My second vision for India’s developme

In [41]:
corpus=[]
for i in range(len(sentences)):
  #print(" before Review",sentences[i])
  review=re.sub('[^a-zA-Z]'," ",sentences[i]) # we are removing all unnecessary numbers and symbols
  #print(" after Review",review)
  review1=review.lower() # converting all words to small letters
  review2=review1.split() # word tokenize happening
  review3=[ps.stem(word) for word in review2 if not word in set(stopwords.words('english'))]
  review4=" ".join(review3)
  corpus.append(review4)

In [42]:
corpus

['three vision india',
 'year histori peopl world come invad us captur land conquer mind',
 'alexand onward greek turk mogul portugues british french dutch came loot us took',
 'yet done nation',
 'conquer anyon',
 'grab land cultur histori tri enforc way life',
 '',
 'respect freedom other first vision freedom',
 'believ india got first vision start war independ',
 'freedom must protect nurtur build',
 'free one respect us',
 'second vision india develop',
 'fifti year develop nation',
 'time see develop nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverti level fall',
 'achiev global recognis today',
 'yet lack self confid see develop nation self reliant self assur',
 'incorrect',
 'third vision',
 'india must stand world',
 'believ unless india stand world one respect us',
 'strength respect strength',
 'must strong militari power also econom power',
 'must go hand hand',
 'good fortun work three great mind',
 'dr vikram sarabhai dept',
 'space profess

In [24]:
# to create the bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
cv=CountVectorizer(max_features=1500)

In [48]:
X=cv.fit_transform(corpus).toarray()

In [49]:
cv.get_feature_names_out()

array(['achiev', 'alexand', 'also', 'among', 'anyon', 'area', 'assur',
       'believ', 'brahm', 'british', 'build', 'came', 'captur', 'career',
       'close', 'come', 'confid', 'conquer', 'consid', 'cultur', 'dept',
       'develop', 'dhawan', 'done', 'dr', 'dutch', 'econom', 'enforc',
       'fall', 'father', 'fifti', 'first', 'fortun', 'four', 'free',
       'freedom', 'french', 'gdp', 'global', 'go', 'good', 'got', 'grab',
       'great', 'greek', 'growth', 'hand', 'histori', 'incorrect',
       'independ', 'india', 'invad', 'lack', 'land', 'level', 'life',
       'loot', 'lucki', 'materi', 'mileston', 'militari', 'mind', 'mogul',
       'must', 'nation', 'nuclear', 'nurtur', 'one', 'onward', 'opportun',
       'other', 'peopl', 'percent', 'portugues', 'poverti', 'power',
       'prakash', 'professor', 'protect', 'rate', 'recognis', 'reliant',
       'respect', 'sarabhai', 'satish', 'second', 'see', 'self', 'space',
       'stand', 'start', 'strength', 'strong', 'succeed', 'term',

In [51]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [67]:
#example
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?'
... ]

In [68]:
vectorizer = CountVectorizer(binary=True)

In [69]:
X = vectorizer.fit_transform(corpus)

In [70]:
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [71]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [60]:
vectorizer2 = CountVectorizer(ngram_range=(1, 3))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['document', 'first', 'first document', 'is', 'is the',
       'is the first', 'the', 'the first', 'the first document', 'this',
       'this is', 'this is the'], dtype=object)

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [73]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [74]:
print(X.shape)

(4, 9)
